import './globals.css'
// make it
import Navbar from './components/Navbar'
import MyProfilePic from './components/MyProfilePic'


export const metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" dark:bg-slate-800">
        <Navbar />
        <MyProfilePic /> 
        {children}
      </body>
    </html>
  )
}
